### ISSUE TITLE
Where can we get images and tiles?

### ISSUE THREAD

**Issue by palla89** [Kruithne/where-in-warcraft#2]
Hi there, was looking through your project and trying to set it up, but couldn't find images. is that intended?

Btw thank you for sharing!!!

**Comment by Kruithne** [comment]
Hey!

The map tiles and images are intentionally not included in this repository for a few reasons, the main one being that there's over 60,000 files in total and having all of them in a GitHub repository wouldn't be ideal. The source code here is intended more of a reference as to how we made the game, rather than a working copy for people to replicate.

If you're interested in how we produce the panoramas and tiles for the game so that you can make your own, there's an in-depth guide on the process on my Patreon → https://www.patreon.com/posts/34521171

Hope this helps!

**Comment by SabineWren** [comment]
Does that mean you aren't accepting contributions?

**Comment by Kruithne** [comment]
Unfortunately we're not accepting contributions of locations for the game. Sorry!
